var data=[{
    "vapros":'Сколько на рисунке треугольников?',
    "image":"img/task4/1.png",
    "otvet" :14,
    "variant1":14,
    "variant2":8,
    "variant3":16,
    "variant4":10,
},{
    "vapros":'Сколько на рисунке четырёхуголников?',
    "image":"img/task4/4.png",
    "otvet" :10,
    "variant1":7,
    "variant2":11,
    "variant3":12,
    "variant4":10, 
},{
    "vapros":'Сколько на рисунке квадратов?',
    "image":"img/task4/2.png",
    "otvet" :10,
    "variant1":9,
    "variant2":8,
    "variant3":10,
    "variant4":12, 
},{
    "vapros":'Сколько на рисунке кругов?',
    "image":"img/task4/3.png",
    "otvet" :4,
    "variant1":5,
    "variant2":4,
    "variant3":8,
    "variant4":10, 
},{
    "vapros":'Сколько на рисунке кругов, треугольников и квадратов?',
    "image":"img/task4/5.png",
    "otvet" :'2, 15, 4',
    "variant1":'2, 14, 5',
    "variant2":'2, 15, 5',
    "variant3":'2, 16, 5',
    "variant4":'2, 15, 4', 
}]