var data=[{
    "gl_img":'./img/image1.png',
    "image1":"./img/image11.png",
    "image2":"./img/image12.png",
    "image3":"./img/image13.png",
    "image4":"./img/image14.png",
    "image5":"./img/image15.png",
    "otver":4
},{
    "gl_img":'./img/image2.png',
    "image1":"./img/image21.png",
    "image2":"./img/image22.png",
    "image3":"./img/image23.png",
    "image4":"./img/image24.png",
    "otver":3
},{
    "gl_img":'./img/image3.png',
    "image1":"./img/image31.png",
    "image2":"./img/image32.png",
    "image3":"./img/image33.png",
    "image4":"./img/image34.png",
    "otver":3
},{
    "gl_img":'./img/image4.png',
    "image1":"./img/image41.png",
    "image2":"./img/image42.png",
    "image3":"./img/image43.png",
    "image4":"./img/image44.png",
    "image5":"./img/image45.png",
    "image6":"./img/image46.png",
    "otver":5
},{
    "gl_img":'./img/image5.png',
    "image1":"./img/image51.png",
    "image2":"./img/image52.png",
    "image3":"./img/image53.png",
    "image4":"./img/image54.png",
    "otver":2
}]