var data=[{
    "speed":2,
    "sound":"./sound/verx_vlevo_vlevo_vniz_vpavo.wav",
    "count":5,
    "position":11
},{
    "speed":2,
    "sound":"./sound/vlevo_vlevo_vpavo_vniz_verx_vlevo_vniz_vpavo_vlevo.wav",
    "count":9,
    "position":15
},{
    "speed":2,
    "sound":"./sound/vniz_vlevo_vniz_vparavo_verx_vpravo.wav",
    "count":6,
    "position":17
},{
    "speed":2,
    "sound":"./sound/vniz_vlevo_vpravo.wav",
    "count":3,
    "position":17
}]